In [1]:
import pandas as pd

def extract_book_details():
    # Ekstraksi data dari CSV
    book_details_df = pd.read_csv("book_details.csv")
    return book_details_df

# Ekstraksi data
book_details_df = extract_book_details()

In [2]:
import sqlite3

def extract_book_reviews():
    # Koneksi ke database SQLite
    conn = sqlite3.connect('book_reviews.db')
    # Ekstraksi data dari database
    book_reviews_df = pd.read_sql_query("SELECT * FROM book_reviews", conn)
    return book_reviews_df

# Ekstraksi data
book_reviews_df = extract_book_reviews()

In [3]:
def extract_books():
    # Koneksi ke database SQLite
    conn = sqlite3.connect('books.db')
    # Ekstraksi data dari database
    books_df = pd.read_sql_query("SELECT * FROM books", conn)
    return books_df

# Ekstraksi data
books_df = extract_books()

In [4]:
import pandas as pd

def transform_book_details(book_details_df):
    def convert_date(date_str):
        try:
            return pd.to_datetime(date_str, format='%B %d, %Y')
        except ValueError:
            return pd.NaT  # Mengembalikan NaT (Not a Time) untuk entri yang tidak dapat diubah

    # Pembersihan data publication_info
    book_details_df['publication_info'] = book_details_df['publication_info'].str.replace(r'\[.*published\s+', '', regex=True).str.strip("']")
    # Ubah ke format tanggal
    book_details_df['publication_info'] = book_details_df['publication_info'].apply(convert_date)
    # Hapus baris dengan nilai NaT
    book_details_df = book_details_df.dropna(subset=['publication_info']).copy()  # Menambahkan .copy() di sini

    # Ekstrak format
    book_details_df['format'] = book_details_df['format'].str.extract(r'(\s*\w+\s*[A-Za-z0-9]+\s*)\']$')
    # Hapus tanda kurung dan tanda kutip dari kolom format
    book_details_df['format'] = book_details_df['format'].str.strip("[]'")
    # Hapus tanda kurung siku dari kolom num_pages
    book_details_df['num_pages'] = book_details_df['num_pages'].str.strip("[]'")

    # Ganti nilai 'None' dengan 0
    book_details_df['num_pages'] = book_details_df['num_pages'].replace(['None', ''], 0)
    # Konversi kolom num_pages menjadi integer
    book_details_df['num_pages'] = book_details_df['num_pages'].astype(int)

    # Mengisi nilai yang hilang pada kolom book_details dengan "Tidak Ada Ringkasan Tersedia"
    book_details_df['book_details'] = book_details_df['book_details'].fillna("Tidak Ada Ringkasan Tersedia")

    return book_details_df

# Proses transformasi
transformed_book_details_df = transform_book_details(book_details_df.copy())  # Menambahkan .copy() di sini

In [5]:
import re

def transform_book_reviews_df(book_reviews_df):
    # Mengubah tipe data kolom 'book_id' menjadi integer
    book_reviews_df['book_id'] = book_reviews_df['book_id'].astype(int)

    # Hilangkan kata-kata 'likes', 'followers', dan 'reviews' dari kolom-kolom tertentu
    book_reviews_df['likes_on_review'] = book_reviews_df['likes_on_review'].str.replace("likes", "")
    book_reviews_df['reviewer_total_reviews'] = book_reviews_df['reviewer_total_reviews'].str.replace("reviews", "")
    book_reviews_df['reviewer_followers'] = book_reviews_df['reviewer_followers'].str.replace(r'\bfollowers?\b', '', regex=True).str.strip()

    # Menghapus baris dengan nilai 'Author' di kolom 'reviewer_followers'
    book_reviews_df = book_reviews_df[book_reviews_df['reviewer_followers'] != 'Author'].copy()

    # Fungsi untuk menghapus karakter "k" dan mengonversi ke integer
    def remove_k_and_convert_to_int(value):
        if pd.isnull(value):  # Jika nilai kosong, kembalikan nilai None
            return None
        else:
            # Gunakan ekspresi reguler untuk menghapus karakter "k" dan konversi ke integer
            numeric_value = re.sub(r'[^\d.]', '', value)
            return float(numeric_value)

    # Daftar kolom yang akan diubah
    columns_to_process = ['likes_on_review', 'reviewer_total_reviews', 'reviewer_followers']

    # Iterasi melalui setiap kolom
    for col in columns_to_process:
        # Menghapus karakter "k" dan mengonversi ke integer untuk setiap nilai dalam kolom
        book_reviews_df[col] = book_reviews_df[col].apply(remove_k_and_convert_to_int)

    # Hapus nilai None di kolom yang sedang diproses
    book_reviews_df[columns_to_process] = book_reviews_df[columns_to_process].fillna(0)

    # Mengubah tipe data kolom 'likes_on_review', 'reviewer_total_reviews', dan 'reviewer_followers' menjadi integer
    book_reviews_df[columns_to_process] = book_reviews_df[columns_to_process].astype(int)

    # Mengubah format tanggal menjadi "YYYY-MM-DD" dan mengonversi ke tipe data datetime
    book_reviews_df['review_date'] = pd.to_datetime(book_reviews_df['review_date'], format='%B %d, %Y')

    # Mengganti nilai None dengan "Rating 1 out of 5"
    book_reviews_df['review_rating'] = book_reviews_df['review_rating'].fillna('Rating 0 out of 5')

    # Membersihkan teks dengan menghapus kata "Rating" dan "out of 5"
    book_reviews_df['review_rating'] = book_reviews_df['review_rating'].str.replace(r'Rating (\d) out of 5', r'\1', regex=True)

    # Mengonversi nilai rating menjadi tipe data integer
    book_reviews_df['review_rating'] = book_reviews_df['review_rating'].astype(int)

    return book_reviews_df

# Proses transformasi
transformed_book_reviews_df = transform_book_reviews_df(book_reviews_df.copy())

In [6]:
def transform_books(books_df):
    # Mengganti nama kolom 'id' menjadi 'book_id'
    books_df = books_df.rename(columns={'id': 'book_id'})
    return books_df

# Proses transformasi
transformed_books_df = transform_books(books_df)

In [81]:
# Menggabungkan DataFrame berdasarkan kolom 'book_id' menggunakan join tipe 'inner'
merged_df = pd.merge(transformed_books_df, transformed_book_details_df, on='book_id', how='inner')
merged_df = pd.merge(merged_df, transformed_book_reviews_df, on='book_id', how='inner')

# Mengonversi tipe data kembali ke integer setelah penggabungan
columns_to_int = ['book_id', 'num_pages', 'likes_on_review', 'reviewer_total_reviews', 'reviewer_followers', 'review_rating', 'reviewer_id']

for col in columns_to_int:
    if col in merged_df.columns:
        merged_df[col] = merged_df[col].fillna(0).astype(int)

# Menghapus kolom 'Unnamed: 0' jika ada
if 'Unnamed: 0' in merged_df.columns:
    merged_df = merged_df.drop(columns=['Unnamed: 0'])
    
# Buat Clean campuran 3 data
clean_merged_books = merged_df
# Membuat DataFrame book_data dengan kolom yang terkait dengan data buku
clean_books_data = clean_merged_books[['book_id', 'title', 'total_books', 'total_votes', 'cover_image_uri', 'book_title', 'book_details', 'format', 'publication_info', 'num_pages', 'genres', 'num_ratings', 'num_reviews', 'average_rating', 'rating_distribution']].drop_duplicates().reset_index(drop=True)
# Membuat DataFrame book_reviews dengan kolom yang terkait dengan ulasan buku
clean_books_reviews = merged_df[['book_id', 'reviewer_id', 'reviewer_name', 'likes_on_review', 'review_content', 'reviewer_followers', 'reviewer_total_reviews', 'review_date', 'review_rating']]

In [85]:
def load(df, file_path):
    try:
        df.to_csv(file_path, index=False)
        print(f"Data successfully saved to {file_path}")
    except Exception as e:
        print(f"Error saving data to {file_path}: {e}")

# Memuat data clean_merged_books ke dalam file CSV
load(clean_merged_books, 'data_clean/clean_merged_books.csv')

# Memuat data clean_books_data ke dalam file CSV
load(clean_books_data, 'data_clean/clean_books_data.csv')

# Memuat data clean_books_reviews ke dalam file CSV
load(clean_books_reviews, 'data_clean/clean_books_reviews.csv')

Data successfully saved to data_clean/clean_merged_books.csv
Data successfully saved to data_clean/clean_books_data.csv
Data successfully saved to data_clean/clean_books_reviews.csv